# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad0915e11eabf32242e6c19f3961e531f434c795d828e2b7aba50b9aaaf2d4843c48a61a90f18be9be7cf9f324457705d75552cc9df5bfeade8d360119a76dba

test:
  secret_key_base: 3037ef1d83cada3e9d39dd6099f0dbcd70e88171380ba2fb509a491709662dc88028fdedc7b65fe9de1747a975f42509c1f334b1603bde5314f5763cd5951355

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
